apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: app1
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/default: 'true'
        io.kompose.service: app1
    spec:
      containers:
        - env:
            - name: CONTAINERIZED_ENV
              value: 'true'
            - name: PORT_APP2
              value: '4002'
          image: asaker/app1:v1
          imagePullPolicy: 'Always'
          name: app1
          ports:
            - containerPort: 4001
          resources: {}
      restartPolicy: Always
      serviceAccountName: 'skyview'
      volumes: null
status: {}
