apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: app1
  name: app1
spec:
  ports:
    - name: '4001'
      port: 4001
      targetPort: 4001
  selector:
    io.kompose.service: app1
status:
  loadBalancer: {}
